# Generated by Django 5.2.3 on 2025-06-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'Grupo Customizado',
                'verbose_name_plural': 'Grupos Customizados',
                'db_table': 'sis_grupos',
            },
        ),
        migrations.CreateModel(
            name='PermissaoCustomizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('auto_descoberta', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permissão Customizada',
                'verbose_name_plural': 'Permissões Customizadas',
                'db_table': 'sis_permissoes',
                'unique_together': {('modulo', 'acao')},
            },
        ),
    ]
