# Generated by Django 5.2.3 on 2025-06-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaocustomizada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='permissaocustomizada',
            index=models.Index(fields=['modulo', 'acao'], name='sis_permiss_modulo_466ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='permissaocustomizada',
            index=models.Index(fields=['nome'], name='sis_permiss_nome_705e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='permissaocustomizada',
            index=models.Index(fields=['ativo'], name='sis_permiss_ativo_9eceba_idx'),
        ),
    ]
